# **Homework 7: Numpy**

## **Due date:** November 3rd, at 2:30 PM.

## **Submission:** Please push your homework to the our GitHub repository, and place it in the 'Homework 7' folder.



---



---



---



---



### **Question 1:**

Use NumPy to solve the following system of linear equations:

In [ ]:
3x+ 2y- z= 1

2x+ 2y+ 4z= -2

-x+ 1/2y- z= 0


In [ ]:
### Answer
import numpy as np
#define coeffiecient
a=np.array([[3,2,-1],[2,2,4],[-1,0.5,-1]])

#constant
b=np.array([1,-2,0])

#solve lineae equation using np.linalg.solve
x=np.linalg.solve(a,b)


print(x)







[ 0.36842105 -0.31578947 -0.52631579]




---



---



### **Question 2:**

Generate an array of 1000 random numbers sampled from a standard normal distribution, then visualize it.

In [ ]:
### Answer


# numpy.random.normal() method
ran_dom = np.random.normal(size=1000)

# create a visualizarion
np.histogram(ran_dom,bins=30)










(array([ 2,  0,  2,  6,  9, 14, 18, 23, 27, 40, 51, 59, 72, 67, 60, 93, 77,
        82, 56, 60, 45, 46, 25, 23, 14, 17,  6,  3,  0,  3]),
 array([-3.08095573, -2.88322402, -2.68549231, -2.48776061, -2.2900289 ,
        -2.09229719, -1.89456548, -1.69683377, -1.49910206, -1.30137035,
        -1.10363864, -0.90590693, -0.70817522, -0.51044351, -0.3127118 ,
        -0.11498009,  0.08275162,  0.28048332,  0.47821503,  0.67594674,
         0.87367845,  1.07141016,  1.26914187,  1.46687358,  1.66460529,
         1.862337  ,  2.06006871,  2.25780042,  2.45553213,  2.65326384,
         2.85099554]))



---



---



### **Question 3:**

Calculate the dot product of the following two vectors using NumPy:

In [ ]:
A = [2, 3, 4]
B = [5, 6, 7]


In [ ]:
### Answer
a=np.array(A)
b=np.array(B)

dot_product=np.dot(a,b)



print(dot_product)





56




---



---



### **Question 4:**

**Random Numbers:**: Generate a 1D array of 20 random integers between 10 and 50. Find out how many of them are even.

In [ ]:
### Answer

random_integers = np.random.randint(10, 51, 20)
print(random_integers)












[23 16 35 40 40 27 21 43 20 12 40 46 21 12 37 33 33 25 39 21]


In [ ]:
even_number = np.count_nonzero(random_integers % 2 == 0)
print(even_number)

8




---



---



### **Question 5:**

**Data Manipulation:** Consider an array of dimension (8,8). Swap the first and last columns.

In [ ]:
### Answer

array = np.random.rand(8, 8)

array[:, [0, -1]] = array[:,[-1, 0]]

print(array)









[[0.60744041 0.29076598 0.67230433 0.98962381 0.57568437 0.20778023
  0.41592783 0.90895626]
 [0.86331689 0.67926215 0.16153397 0.15874283 0.3943915  0.850902
  0.1023431  0.4325694 ]
 [0.18781545 0.351803   0.51971874 0.3733716  0.32886049 0.03461104
  0.43976346 0.72644888]
 [0.94202248 0.1880426  0.46456753 0.29022819 0.45210322 0.08032995
  0.58923985 0.15442851]
 [0.47256522 0.77191439 0.69886647 0.53759101 0.72937028 0.83030763
  0.37801637 0.92048494]
 [0.29738483 0.94823376 0.42113825 0.63317856 0.34455029 0.674145
  0.59384572 0.6845686 ]
 [0.14585196 0.61383686 0.87525692 0.47264851 0.48503515 0.57195032
  0.23890067 0.89992859]
 [0.51373137 0.60241982 0.59105463 0.86754497 0.50925045 0.30158699
  0.10494582 0.48627563]]




---



---



### **Question 6:**

**Given a 2D NumPy array data, extract the following subsets:**

- The first row.
- The last column.
- The subarray consisting of the first two rows and the last two columns.

In [ ]:
## Answer


first_row = data[0, :]







SyntaxError: ignored



---



---



### **Question 7:**

**Statistics:** Create a matrix of shape (5,5), find the mean and variance of the values in its 3rd column.

In [ ]:
### Answer


matrix = np.random.rand(5, 5)

third_column = matrix[:, 2]
mean_third_column = np.mean(third_column)

variance_of_3columns=np.var(third_column)


variance_of_3columns







0.058682045408257354



---



---



---



### **Question 8:**

**Linear Algebra:** Given a 4x4 matrix, compute its transpose and then find the dot product of the matrix with its transpose.

In [ ]:

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

In [ ]:
### Answer



x= np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])



y=np.transpose(x)

z= np.dot(x, y)


print(z)









[[ 30  70 110 150]
 [ 70 174 278 382]
 [110 278 446 614]
 [150 382 614 846]]




---



---



### **Question 9:**

**Array Operations:** Create two matrices, then Compute the element-wise multiplication of two matrices, then sum the values in each row of the resulting matrix.

In [ ]:
### Answer


x1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

x2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

x1_x2=np.multiply(x1, x2)

np.sum(x1_x2)









165



---



---



---



### **Question 10:**

**Advanced Array Creation:** Create a 2D array of shape (7,7) where the border consists of ones and the inner part consists of zeros.

In [ ]:

array_2D = np.ones((7, 7))


array_2D[1:-1, 1:-1] = 0

print(array_2D)



[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
