## **Question 1: Use NumPy to solve the following system of linear equations:**

3x+ 2y- z= 1

2x+ 2y+ 4z= -2

-x+ 1/2y- z= 0

In [42]:
import numpy as np
# The matrix of coefficients
A = np.array([[3, 2, -1], [2, 2, 4], [-1, 0.5, -1]])
# Defining the vector of constants
b = np.array([1, -2, 0])
# Solve the system of equations
x = np.linalg.solve(A, b)
# Solution
print(x)

[ 0.36842105 -0.31578947 -0.52631579]


## **Question 2: Generate an array of 1000 random numbers sampled from a standard normal distribution, then visualize it.**

In [41]:
random_num=np.random.random(size=1000) ##Creating random numbers with size 1000
random_num

array([4.63286577e-01, 3.26846093e-03, 7.79895218e-01, 8.53225535e-01,
       7.17838933e-01, 3.10306977e-01, 5.40147922e-01, 3.96267852e-01,
       2.46482345e-03, 6.46487708e-01, 5.84535671e-01, 1.82608828e-01,
       5.71474720e-01, 3.39272316e-01, 2.32658125e-01, 4.44669395e-01,
       3.55038909e-03, 2.32104359e-01, 6.27225292e-01, 3.86483950e-02,
       2.54368981e-01, 9.08980773e-01, 7.23441404e-01, 9.88753848e-01,
       2.58688104e-01, 8.30614339e-01, 2.25319606e-01, 4.37240269e-01,
       6.72657241e-02, 8.15069128e-01, 7.77695592e-01, 8.66103249e-01,
       8.95054676e-01, 3.02918157e-01, 8.68924551e-01, 6.62635369e-01,
       5.00976738e-01, 4.65269631e-01, 6.25697852e-02, 2.68944277e-01,
       9.70374773e-01, 2.94168852e-01, 8.59552550e-01, 6.20496522e-02,
       8.60048246e-02, 4.07769999e-01, 1.24210355e-01, 1.40435284e-01,
       7.60952471e-01, 5.89907785e-01, 7.20992950e-01, 3.15278863e-01,
       6.03941292e-01, 6.73133979e-01, 1.31668095e-01, 1.04471782e-01,
      

# **Question 3: Calculate the dot product of the following two vectors using NumPy:**

In [40]:
import numpy as np
num1= np.array([2, 3, 4]) ##Create array
num2= np.array([5, 6, 7]) ## Create array
dot_product = np.dot(num1, num2) #dot product
print(dot_product)

56


# **Question 4. Random Numbers:** Generate a 1D array of 20 random integers between 10 and 50. Find out how many of them are even.

In [39]:
from numpy import random
x=random.randint(10,50, size=(20)) ##Random numbers from 10 to 50

print(x)

[44 17 15 36 26 41 23 38 14 25 18 39 35 15 44 37 39 21 18 16]


# **Question 5. Data Manipulation:** Consider an array of dimension (8,8). Swap the first and last columns.

In [29]:
import numpy as np
a = np.ones((8,8)) #Create an array
a[:, [0, -1]] = a[:, [-1, 0]] ##Swaping the columns
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

# **Question 6: Given a 2D NumPy array data, extract the following subsets:**

- The first row.
- The last column.
- The subarray consisting of the first two rows and the last two columns.

In [30]:
import numpy as np
# Create a sample 2D array
values = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
# Extract the subsets
first_row = values[0]
last_column = values[:,-1]
subarray = values[:2,-2:]
# Print the results
print("First row:", first_row)
print("Last column:", last_column)
print("Subarray:", subarray)

First row: [1 2 3 4]
Last column: [ 4  8 12]
Subarray: [[3 4]
 [7 8]]


# **Question 7.Statistics:** Create a matrix of shape (5,5), find the mean and variance of the values in its 3rd column.

In [31]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
mean = np.mean(matrix[:,2], axis=0)
var = np.var(matrix[:,2], axis=0)

In [32]:
mean

13.0

In [33]:
var

50.0

# **Question 8.Linear Algebra: Given a 4x4 matrix, compute its transpose and then find the dot product of the matrix with its transpose.**

In [34]:
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
transpose = np.transpose(matrix)
dot_product = np.dot(matrix, transpose)
print("The transpose of the matrix is:")
print(transpose)
print("The dot product of the matrix and its transpose is:")
print(dot_product)

The transpose of the matrix is:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
The dot product of the matrix and its transpose is:
[[ 30  70 110 150]
 [ 70 174 278 382]
 [110 278 446 614]
 [150 382 614 846]]


# **Question 9. Array Operations: Create two matrices, then Compute the element-wise multiplication of two matrices, then sum the values in each row of the resulting matrix.**

In [35]:
import numpy as np
A = [[1, 2], [3, 4]] ## Create the Arrays
B = [[5, 6], [7, 8]]

C = np.multiply(A, B) ## Compute calculation
D = np.sum(C, axis=1)


In [36]:
C

array([[ 5, 12],
       [21, 32]])

In [37]:
D

array([17, 53])

# **Question 10.Advanced Array Creation:Create a 2D array of shape (7,7) where the border consists of ones and the inner part consists of zeros.**

In [38]:
import numpy as np # import the library
x = np.ones((7,7)) # create a 7x7 array filled with ones
x[1:-1,1:-1] = 0 # set the inner elements to zero by slicing
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
